03 checkpoint
niksaz/spbau-scala pull request #2
Opened 2017-09-24 22:21 UTC by niksaz

2017-09-25 08:55 UTC, adkozlov commented
Добавьте, пожалуйста, @dzharkov в качестве ревьюера.

2017-09-30 08:08 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы 04.10 23:59. Не забудь написать “@dzharkov” в комменте к PR

2017-09-30 08:08 UTC, dzharkov commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarEvent.scala
> +    "from " + startDateTime.toString + " to " + endDateTime.toString +
Вообще было бы круто, чтобы формат времени ивентов был более очеловеченным
Например: "Сегодня с 08:00 до 10:00"
И да, в рамках `toString` это вряд ли удастся сделать
Ну и, если получится, было бы круто хоть что-нибудь подобное поддержать в парсере

2017-09-30 08:08 UTC, dzharkov commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarStorage.scala
> +      userCalendarEvents.sortWith(
sortBy?

2017-09-30 08:08 UTC, dzharkov commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarStorage.scala
> +    while (sortedEventsIterator.hasNext && nextEvents.size < numberOfEvents) {
filter + take?

2017-09-30 08:08 UTC, dzharkov commented on src/test/scala/ru/spbau/sazanovich/nikita/bot/parser/MessageParserTest.scala
> +  val dateFormatter: DateTimeFormatter = DateTimeFormat.forPattern("dd-MM-yyyy HH:mm")
За тесты +

2017-10-03 09:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarEvent.scala
> +    "from " + startDateTime.toString + " to " + endDateTime.toString +
Мне казалось, что для прототипа, это выглядело ничего.
Но Вы правы. Я добавил возможность использовать today, tomorrow в парсере и изменил соответствующим образом форматирование событий в выводе.

2017-10-03 09:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarStorage.scala
> +      userCalendarEvents.sortWith(
Спасибо, упростил.

2017-10-03 09:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/bot/CalendarStorage.scala
> +    while (sortedEventsIterator.hasNext && nextEvents.size < numberOfEvents) {
Действительно.

2017-10-03 09:39 UTC, niksaz commented
Спасибо Вам за review, @dzharkov. Посмотрите еще раз, пожалуйста.

2017-10-07 08:59 UTC, dzharkov approved these changes
Ок, 10/10

2017-10-07 08:59 UTC, dzharkov commented on src/test/scala/ru/spbau/sazanovich/nikita/bot/parser/MessageParserTest.scala
> +         "Create event today from 10:00 to 12:00 named \"Surprise\"")
Круто!

2017-12-03 20:50 UTC, closed without merging