04 checkpoint
niksaz/spbau-scala pull request #3
Opened 2017-10-01 22:18 UTC by niksaz

MultiSet implementations: Mutable & Immutable ones.

2017-10-07 22:42 UTC, adkozlov requested changes
В целом нормально.
Местами не хватает использования библиотечных методов, кое-где определенный бойлер-плейт наблюдается.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    if (getCount(elem) > 0) Option.apply(elem) else Option.empty
`Some(elem) else None`.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def apply(elem: A): Boolean = {
Подобные методы можно писать без фигурных скобок (хотя не обязательно).

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
Публичное проперти, которое используется только внутри.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def add(elem: A): Int = addCount(elem, 1)
Единица просится в качестве аргумента по умолчанию (такой вызов дважды используется).

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    assert(count > 0)
Ну это уже, мне кажется, излишество.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    var equalElementsCount = getCount(elem)
Изменяемое состояние, без которого можно легко обойтись.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    elementCountMap.update(elem, equalElementsCount)
Можно использовать метод `put`, он как раз вернет значение.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  @VisibleForTesting
Эту задачу в общем-то и решает модификатор доступа.
Мне это кажется определенным овердизайном.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
И конструктор с таким аргументом не используется.
Так что лучше вынести это проперти в тело класса.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Лучше использовать более специфичные методы. В данном случае `assertEquals`.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.get("hello") == Option("hello"))
В таких случаях принято писать`Some("hello")`.
Второй вариант: `multiSet.get("hello").contains("hello")`.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.get("hola") == Option.empty)
Я уже писал выше, принято писать `None`.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    val mappedMultiSet = multiSet.map(x => x * 2)
Тут можно анонимный аргумент использовать.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    for ((element, count) <- elementCountMap) {
Подобный бойлер-плейт встречается дальше во всех методах.
Это желательно обобщить.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    for ((element, count) <- this.elementCountMap) {
`this`, как и в Java, принято использовать только, если без него совсем не обойтись.
Я понял, что сделано ради единообразия, но мне кажется излишним.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elements = ArrayBuffer.empty[A]
Более принятый вид: `mutable.ArrayBuffer[A]()`.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/immutable/TestParent.scala
> +class TestParent(val name: String) {
Оба эти класса лучше было бы объявить в companion object самого теста.

2017-10-07 22:42 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSetTest.scala
> +class MultiSetTest extends FunSuite {
Тут все те же комментарии, что и для `mutable.MutliSetTest`.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    if (getCount(elem) > 0) Option.apply(elem) else Option.empty
Во-первых, `getCount(elem) > 0` эквивалентно `apply(elem)` или `this(elem)`.
Во-вторых, это достаточно странный контракт метода -- возвращать переданное значение. Это можно даже сделать не методом класса, так как доступа к внутреннему состоянию нет.

Ожидается, что информация будет появляться от вызова метода. Например, количество элементов.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.exists(e => e._1 == elem)
Вызов `iterator` не нужен.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.exists(e => e._1 == elem)
Обращение к полям кортежа лучше избегать по возможности.
Альтернатива:
```scala
elementCountList.exists {
  case (e, _) => e == elem
}
```

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +  def get[B >: A](elem: B): Option[B] = {
Здесь тот же комментарий про уместность метода, что и для `mutable` версии.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.find(e => e._1 == elem).map(e => e._1)
Эквивалент:
```scala
elementCountList.collectFirst {
  case (e, _) if e == elem => elem
}
```

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.foreach(e => {
При применении функции более принят такой синтаксис:
```scala
foreach { e =>
}
```

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    var elemCount = 0
Всю эту конструкцию можно заменить на свертку.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +      if (e._1 == elem) {
Эквивалент:
```scala
elementCountList.foreach {
  case (e, count) if e == elem => elemCount += count
}
```

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.exists(e => e._1 == elem)
Плюс дубликация кода. Это `get(elem).isDefined`.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    this(immutable.List(elementCountMap.toSeq:_*))
`this(elementCountMap.toList)`

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +class MultiSet[+A] private (val elementCountList: immutable.List[(A, Int)]) {
Не самый очевидный выбор коллекций для хранения элементов.
Более правильная реализация этой идеи: хранить через `private val elementsWithCount: Map[A, Int]`. А при создании собирать в изменяемую мапу, и ее один раз конвертировать.
И метод `apply` в companion object мог бы этим и заниматься.

2017-10-07 22:42 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +import scala.collection.immutable
Неизменяемые структуры принято использовать без префикса.

2017-10-07 22:58 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +  private def mergeInElementCountMap[A](
Очень странный метод.
Это же, вроде, аналог метода `mutable.MutliSet#addCount`.
Вынесение его в качестве "статического" на производительность не влияет, но значительно ухудшает читаемость.

2017-10-08 06:23 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
Действительно.

2017-10-08 20:47 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
Спасибо.

2017-10-08 20:49 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
Действительно.

2017-10-08 20:53 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def apply(elem: A): Boolean = {
Да, все же не знаю, какова конвенция в Scala насчет этого. Я пишу без скобок, когда весь метод это просто делагация другому методу. Наверняка, можно более часто это делать, Вы правы.

2017-10-08 20:53 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def add(elem: A): Int = addCount(elem, 1)
Спасибо.

2017-10-08 20:55 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    assert(count > 0)
Хм, возможно. С текущими операциями сложно напутать. Все же, хотелось, чтобы не было элементов с отрицательным количеством и проверка, кажется, невеликой ценой. Все же, пользоваться надо просто правильно. :) Удалил.

2017-10-08 20:56 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    var equalElementsCount = getCount(elem)
Действительно.

2017-10-08 20:57 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    elementCountMap.update(elem, equalElementsCount)
Он же вернет предыдущее значение, а хотелось бы новое, не правда ли?

2017-10-08 21:08 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  @VisibleForTesting
Возможно, я не понял, что Вы имеете в виду под овердизайном, но все же указания для читающего, что это лишь для тестов, а не для использованию кодом пакета, кажется неплохой затеей. Или Вы хотите сказать, если метод private семантически, то и должен быть таким?

2017-10-08 21:11 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    if (getCount(elem) > 0) Option.apply(elem) else Option.empty
Справедливо, но все же utility методы класса, которые делают за вас что-то, кажутся полезными и стоящими, чтобы их писать в классе (как закутывание значения в optional в зависимости от его содержания). Но Вы правы насчет его полезности: можно и реализовать пользователю.

2017-10-08 21:35 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    for ((element, count) <- elementCountMap) {
Справедливо, спасибо.

2017-10-08 21:39 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elementCountMap: mutable.HashMap[A, Int] = mutable.HashMap.empty[A, Int]) {
Но все же, нужно теперь для того, чтобы в объединении инициализировать первым set-ом.

2017-10-08 21:41 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    for ((element, count) <- this.elementCountMap) {
Да, все время войны, насчет лаконичности и (читаемости?). Не видел строгих соглашений по этому поводу еще. Давайте будем лаконичны здесь.

2017-10-08 21:43 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    val elements = ArrayBuffer.empty[A]
Буду знать, спасибо.

2017-10-08 21:44 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def apply(elem: A): Boolean = {
Если возвращаемый тип не `Unit`, то можно спокойно убирать скобки.

2017-10-08 21:46 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    elementCountMap.update(elem, equalElementsCount)
К нему снова можно прибавить значение. :)
Я просто заметил, что так можно было бы сделать.

2017-10-08 21:48 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    if (getCount(elem) > 0) Option.apply(elem) else Option.empty
Вообще интерфейс должен оставаться емким и минимальным по возможности.
Данный метод можно сделать утильным и объявить в companion object, так как он реализуем через публичный интерфейс класса.

2017-10-08 21:51 UTC, adkozlov commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  @VisibleForTesting
Во-первых, да. Есть разные взгляды на этот вопрос, но я обычно за то, чтобы тестировать класс целиком (as is).
А овердизайном мне кажется использование сторонних библиотек для этого домашнего задания.

2017-10-08 21:57 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Разумно. Спасибо. Использовал Google Truth, т.к. там сообщения поприятнее. А в Scala чем пользуются тогда? Java библиотеками для проверки?

2017-10-08 21:59 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Это статические методы из `org.junit.Assert`.

2017-10-08 22:05 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Ага, спасибо.
Но мне кажется, Google Truth представляет больше функциональности, по сравнению с JUnit. И читаемость лучше. Если Вы не настаиваете на библиотеке, то я предпочту использовать ее.

2017-10-08 22:07 UTC, adkozlov commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Тестовый фреймворк все подбирают для себя.
Я лично за использование ScalaTest для Scala. Очень удобно.

2017-10-08 22:12 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +  def apply(elem: A): Boolean = {
Хорошее правило. Благодарю.

2017-10-08 22:13 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSet.scala
> +    elementCountMap.update(elem, equalElementsCount)
Верно подмечено.

2017-10-08 22:17 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.getCount(5) == 1)
Справедливо.

2017-10-08 22:18 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.get("hello") == Option("hello"))
Ага, точно. Не знал о Some & None. Исправил.

2017-10-08 22:18 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    assert(multiSet.get("hola") == Option.empty)
Учтено.

2017-10-08 22:19 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/mutable/MultiSetTest.scala
> +    val mappedMultiSet = multiSet.map(x => x * 2)
Удобно. Спасибо.
[Вот что неудобно, так что Вам приходит каждый мой ответ. Неужели на GitHub нет функциональности отправления комментариев всем только тогда, когда я нажму reply? Что имеет смысл.]

2017-10-09 06:40 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +import scala.collection.immutable
Спасибо: исправил.

2017-10-09 06:40 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/immutable/TestParent.scala
> +class TestParent(val name: String) {
Учтено.

2017-10-09 06:41 UTC, niksaz commented on src/test/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSetTest.scala
> +class MultiSetTest extends FunSuite {
Учтено.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +class MultiSet[+A] private (val elementCountList: immutable.List[(A, Int)]) {
Тогда бы Set был бы не ковариантный и получается просто чуть ли не копия другого класса. Этот вариант хоть и не славится производительностью, но зато с covariantностью поразвлекаться пришлось.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    this(immutable.List(elementCountMap.toSeq:_*))
Учтено.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.exists(e => e._1 == elem)
Учтено.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    elementCountList.iterator.exists(e => e._1 == elem)
Ну это все же спорно. То есть у меня сейчас есть getCount. Видно, что getCount > 0 <-> apply. Но все же хорошо иметь оба метода. Вы упомянули ранее, что можно переместить в companion object такие, но тогда же вызывать их будет очень неудобно.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +  def get[B >: A](elem: B): Option[B] = {
Удалил.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +    var elemCount = 0
Действительно, спасибо.

2017-10-09 07:37 UTC, niksaz commented on src/main/scala/ru/spbau/sazanovich/nikita/collect/immutable/MultiSet.scala
> +  private def mergeInElementCountMap[A](
Вы правы, это аналог этого метода. Но этот же для mutable.HashMap. А сейчас мы строим immutable.MultiSet. Вы предлагаете при построении собирать все в mutable.MultiSet?

2017-10-09 07:39 UTC, niksaz commented
Спасибо за review, @adkozlov. Узнал многие методы библиотеки и конвенции Scala. :)
Взгляните, пожалуйста, еще разок.

2018-01-15 22:13 UTC, closed without merging